CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255)
);
CREATE TABLE FOOD_ITEMS (
    FOOD_ID NUMBER PRIMARY KEY,
    FOOD_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PRICE NUMBER(10, 2) NOT NULL,
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(15)
);
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE DEFAULT SYSDATE,
    TOTAL_AMOUNT NUMBER(10, 2),
    STATUS VARCHAR2(50),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    FOOD_ID NUMBER,
    QUANTITY NUMBER NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (FOOD_ID) REFERENCES FOOD_ITEMS(FOOD_ID)
);
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (1, 'Appetizers', 'Small dishes to start your meal');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (2, 'Main Course', 'Hearty meals to satisfy your hunger');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION) VALUES (3, 'Desserts', 'Sweet dishes to end your meal');

INSERT INTO FOOD_ITEMS (FOOD_ID, FOOD_NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES (1, 'Bruschetta', 'Toasted bread topped with tomatoes and basil', 6.50, 1);
INSERT INTO FOOD_ITEMS (FOOD_ID, FOOD_NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES (2, 'Lasagna', 'Pasta layered with meat and cheese', 12.00, 2);
INSERT INTO FOOD_ITEMS (FOOD_ID, FOOD_NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES (3, 'Tiramisu', 'Coffee-flavored dessert', 5.00, 3);

INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME, EMAIL, PHONE) VALUES (1, 'Alice Smith', 'alice@example.com', '555-1234');
INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME, EMAIL, PHONE) VALUES (2, 'Bob Johnson', 'bob@example.com', '555-5678');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, TOTAL_AMOUNT, STATUS) VALUES (1, 1, 18.50, 'Pending');

INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, FOOD_ID, QUANTITY) VALUES (1, 1, 1, 2);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, FOOD_ID, QUANTITY) VALUES (2, 1, 2, 1);

SELECT * FROM CATEGORIES;

SELECT * FROM FOOD_ITEMS;

SELECT FI.FOOD_NAME, FI.PRICE, C.CATEGORY_NAME 
FROM FOOD_ITEMS FI 
JOIN CATEGORIES C ON FI.CATEGORY_ID = C.CATEGORY_ID;

SELECT C.NAME, COUNT(O.ORDER_ID) AS Total_Orders 
FROM CUSTOMERS C 
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID 
GROUP BY C.NAME;

SELECT FI.FOOD_NAME, SUM(OD.QUANTITY * FI.PRICE) AS Total_Sales
FROM ORDER_DETAILS OD
JOIN FOOD_ITEMS FI ON OD.FOOD_ID = FI.FOOD_ID
GROUP BY FI.FOOD_NAME;
